#!/usr/bin/env bash
# Bash script that displays information about the sub-domains of ip addresses

#Function to get DNS information
get_dns_info() {
	domain=$1
	subdomain=$2

	if [ -z "$subdomain" ]; then
		subdomains=("www" "lb-01" "web-01" "web-02")
	else
		subdomains=("$subdomain")
	fi

	for sub in "${subdomains[@]}"; do
		ip_address=$(dig +short "$sub.$domain")
		if [ -z "$ip_address" ]; then
			echo "The subdomain $sub.$domain does not have a DNS record."
		else
			record_type=$(dig "$sub.$domain" | grep -A1 'ANSWER SECTION:' | awk '/IN/ {print $4}')
			echo "The subdomain $sub is a $record_type record and points to $ip_address"
		fi
	done
}

get_dns_info "$1" "$2"
