#!/usr/bin/env bash
# Script that transfers a file from client to a server
# Accepts 4 parameters which are:
# the path to the file to be transferred, the IP of the server the file will
# be transferred to, the username scp connects with and the path to the SSH
# private key that scp uses

if [ $# -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    PATH_TO_FILE=$1
    IP=$2
    USERNAME=$3
    PATH_TO_SSH_KEY=$4

    scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP:~/"
fi
