#!/usr/bin/env bash
# Script that configures Nginx server to have
# a custom 4040 page that contains the string
# Ceci n'est pas une page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.html
sed -i "/server_name _;/a\\\trewrite ^/redirect_me https://github.com/Henshaw-knight permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404_error.html
sed -i "/server_name _;/a\\\terror_page 404 /404_error.html;\n\tlocation = /404_error.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}" /etc/nginx/sites-available/default
sudo service nginx restart
