#!/usr/bin/env bash
# Script that adds a custom Nginx response header
# Aims to help track which web server is answering our HTTP requests
sudo apt-get -y update
sudo apt-get -y install nginx
sed -i "/include \/etc\/nginx\/sites-enabled\/\*;/a\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
