#!/usr/bin/env bash
# Script that installs and configures HAproxy, a load balancer, on the server
sudo apt-get -y update
sudo apt-get -y install haproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
echo "
frontend http
    bind *:80
    mode http
    default_backend web_backend

backend web_backend
    balance roundrobin
    server 106174-web-01 54.144.43.187:80 check
    server 106174-web-02 100.26.252.225:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

# check if configuration made is valid
sudo haproxy -f /etc/haproxy/haproxy.cfg -c

sudo service haproxy restart
