#!/usr/bin/env bash
# Script that displays the content of the current directory
# in a list format
# where only the part of the name after the first dahs is displayed

for file in *
do
  #check if the file is not a hidden file
  if [[ "$file" != .* ]]
  then
    echo "$file" | cut -d'-' -f2
  fi
done
