#!/usr/bin/env bash
# Bash script that fixes container so that Nginx is running as the nginx user and is listening on all active IPs on port 8080
pkill apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 444 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
su nginx -c "service nginx restart"
