#!/usr/bin/env bash
# Another version of the debugging bash script
pkill apache2
sed -i "s/user www-data/user nginx/g" /etc/nginx/nginx.conf
chmod 444 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
